import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import NextAuthProvider from "@/components/next-auth-session-provider";

const manrope = Manrope({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {
    const { locale } = await params.catch(() => ({ locale: "en" }));

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={`${manrope.className} dark:bg-foreground text-font-primary dark:text-background antialiased`}>
                <NextAuthProvider>
                    <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
                        {children}
                    </ThemeProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
